services:
  - type: web
    name: clinic_scheduler
    env: python
    region: frankfurt  
    plan: free
    disk: 512
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --no-input
      python manage.py collectstatic --no-input
    startCommand: gunicorn clinic_scheduler.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        fromSecret: django-secret-key
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        # Either set to "*" to allow all, or comma-separate your domains
        value: "clinic-scheduler-lvvb.onrender.com"
secrets:
  - name: django-secret-key
    secure: 713deaac26637e9bb51758a14d2e6b26


