# Generated by Django 4.2 on 2025-06-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_medicaltestschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltestschedule',
            name='student',
            field=models.ForeignKey(blank=True, help_text="(temporary) link to the student's profile", limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_tests', to='appointments.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('CPT', 'Computer Science'), ('PHY', 'Physics'), ('CSS', 'Cyber Security Science'), ('IMT', 'Information and Media Technology')], help_text='Student’s department', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='matric_no',
            field=models.CharField(blank=True, help_text='For students: their matriculation number', max_length=20, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='medicaltestschedule',
            unique_together={('student',)},
        ),
        migrations.RemoveField(
            model_name='medicaltestschedule',
            name='department',
        ),
        migrations.RemoveField(
            model_name='medicaltestschedule',
            name='matric_no',
        ),
        migrations.RemoveField(
            model_name='medicaltestschedule',
            name='name',
        ),
    ]
